name: Kymatio Conda CI

on:
    push:
        paths:
          - "kymatio/*"
          - "tests/*"
          - ".github/workflows/*"
          - ".coveragerc"
          - "requirements.txt"
          - "requirements_optional.txt"
          
    pull_request:
        paths:
          - "kymatio/*"
          - "tests/*"
          - ".github/workflows/*"
          - ".coveragerc"
          - "requirements.txt"
          - "requirements_optional.txt"

jobs:
    build-conda:
        if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

        runs-on: ubuntu-20.04

        strategy:
            matrix:
                python-version: [3.6, 3.7]
                pytorch-version: [1.7, 1.8]

        env:
            CONDA_ENV: test-env-py${{ matrix.python-version }}-torch${{ matrix.pytorch-version }}

        steps:
            - uses: actions/checkout@v1
            - name: Set up Conda
              run: |
                  conda config --set always_yes yes --set changeps1 no

                  conda update -q conda

                  conda info -a

                  conda create -q -n ${CONDA_ENV} python=${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  conda install -n ${CONDA_ENV} numpy scipy pytest pytest-cov coverage
                  conda install -n ${CONDA_ENV} pytorch=${{ matrix.pytorch-version }} torchvision cpuonly -c pytorch

                  conda run -n ${CONDA_ENV} python3 -m pip install --upgrade pip

                  conda run -n ${CONDA_ENV} python3 -m pip install "tensorflow>=2.0.0a"
                  conda run -n ${CONDA_ENV} python3 -m pip install scikit-learn

                  conda run -n ${CONDA_ENV} python3 -m pip install -r requirements.txt
                  conda run -n ${CONDA_ENV} python3 -m pip install -r requirements_optional.txt
            - name: Set up Kymatio
              run: conda run -n ${CONDA_ENV} python3 setup.py develop
            - name: Test
              run: >
                  
                  conda run -n ${CONDA_ENV} pytest --cov=kymatio --cov-report=xml

            - name: codecov upload coverage
              uses: codecov/codecov-action@v1 
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                directory: ./
