name: ssqueezepy CI

on:
    pull_request:
      paths:
        - "ssqueezepy/*"
        - "tests/*"
        - ".github/workflows/*"
        - ".coveragerc"
        - "requirements.txt"
        - "requirements-dev.txt"

jobs:
    build-conda:
        if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: [3.7]

        steps:
            - uses: actions/checkout@v1
            - name: Add Conda to path
              run: echo $CONDA >> $GITHUB_PATH
              
            - name: Set up Conda
              run: |
                  conda config --set always_yes yes --set changeps1 no
                  conda install setuptools
                  conda install conda
                  conda update --force conda
                  conda info -a
                  conda create -q -n test-env python=${{ matrix.python-version }}
                  
            - name: Install dependencies
              run: |
                  conda install pytest pytest-cov -c conda-forge
                  conda install numpy -c conda-forge -n test-env
                  
                  conda run -n test-env python3 -m pip install --upgrade pip
                  conda run -n test-env python3 -m pip install -r requirements.txt
                  
            - name: Set up ssqueezepy
              run: conda run -n test-env python3 setup.py develop
              
            - name: Test
              run: >
                  conda run -n test-env pytest tests/ -s --cov=ssqueezepy --cov-report=xml
                  
            - name: codecov upload coverage
              uses: codecov/codecov-action@v1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                directory: ./
